name: Integration Test
on:
  repository_dispatch:
    types: [run-status-changed]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      # with:
      #   persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
      #   fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
    - name: Create local changes
      uses: mlopstemplates/markdown_convertor@master
      with: 
        payload: {{ github.event.client_payload.data }}
        json_file: "modeltrackingdata.json"

    - name: Commit files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git commit -m "Add changes" -a
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}